### PR TITLE
Migrate golo version

### PR DESCRIPTION
**Pull request by yloiseau**
Change the golo version to 3.1 and allows to load code from the URL

### CODE REVIEW

**Comment by yloiseau** [comment]
This should allow the second point of https://github.com/eclipse/golo-lang/issues/383

**Review by jponge — APPROVED** [review]

**Comment by jponge** [comment]
Thanks!

**Comment by yloiseau** [comment]
could you redeploy the service please? :innocent: :kissing_heart:

**Comment by jponge** [comment]
Ok I'll do, I just need to go back to a laptop with the AppEngine
credentials ready to work :-)

**Comment by yloiseau** [comment]
Thanks... I need it because I have a pending branch where the code samples in the `golo doc` have a link to be opened in the console :smile:

**Comment by jponge** [comment]
@yloiseau Done!

**Comment by yloiseau** [comment]
@jponge thanks

**Comment by yloiseau** [comment]
Ooops... seems like I broke everything... I did only test with jetty, but GAE does not like `Optional`...

**Pull request merged**
